### ISSUE TITLE
wrong information about docker images

### ISSUE THREAD

**Issue by masoudniki** [mrbardia72/docker-Interview-Questions-and-Answers#1]
https://github.com/mrbardia72/docker-Interview-Questions-and-Answers/blob/9c6cb411a5483caedf55dc6145506c163e44f091/docker-image.md?plain=1#L3-L4

in the docker image questions in the first question ```What is a Docker image?``` It mentioned that an image contains an operating system but an operating system without a kernel is not complete so inside a docker image we can't see any kernel **so it can not be correct to say that an image contains the operating system**

**Comment by mrbardia72** [comment]
> https://github.com/mrbardia72/docker-Interview-Questions-and-Answers/blob/9c6cb411a5483caedf55dc6145506c163e44f091/docker-image.md?plain=1#L3-L4
> 
> in the docker image questions in the first question `What is a Docker image?` It mentioned that an image contains an operating system but an operating system without a kernel is not complete so inside a docker image we can't see any kernel **so it can not be correct to say that an image contains the operating system**

tnx Masoud
